spring:
  jpa:
    show-sql: true

logging:
  level:
    com.kardexis: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "super-secret-key-that-must-be-at-least-32-characters-long-for-security"
    access-token-minutes: 15
    refresh-token-days: 7